import 'package:flutter/material.dart';

import 'icon_tags.dart';

class IconMapper {
  static const List<String> kAccountIconKeys = <String>[
    'account_balance',
    'account_balance_wallet',
    'credit_card',
    'wallet',
    'payments',
    'savings',
    'local_atm',
    'attach_money',
    'currency_rupee',
    'currency_bitcoin',
    'card_giftcard',
    'apartment',
    'work',
    'school',
    'home',
    'flight',
    'store',
    'shopping_bag',
    'favorite',
    'trending_up',
  ];

  static const List<String> kCategoryIconKeys = <String>[
    'wallet',
    'credit_card',
    'account_balance',
    'savings',
    'payments',
    'local_atm',
    'card_giftcard',
    'assignment_return',
    'restaurant',
    'fastfood',
    'local_cafe',
    'local_bar',
    'lunch_dining',
    'local_grocery_store',
    'local_drink',
    'cake',
    'directions_car',
    'two_wheeler',
    'electric_scooter',
    'directions_bus',
    'train',
    'flight',
    'local_gas_station',
    'local_taxi',
    'shopping_cart',
    'shopping_bag',
    'checkroom',
    'devices',
    'weekend',
    'redeem',
    'electrical_services',
    'water_drop',
    'local_fire_department',
    'wifi',
    'phone_android',
    'house',
    'subscriptions',
    'receipt_long',
    'local_hospital',
    'medication',
    'fitness_center',
    'emergency',
    'psychology',
    'movie',
    'music_note',
    'sports_esports',
    'menu_book',
    'sports_soccer',
    'live_tv',
    'content_cut',
    'spa',
    'face',
    'watch',
    'palette',
    'auto_awesome',
    'home',
    'build',
    'handyman',
    'cleaning_services',
    'chair',
    'hotel',
    'luggage',
    'beach_access',
    'hiking',
    'card_travel',
    'tour',
    'work',
    'business_center',
    'laptop',
    'groups',
    'print',
    'school',
    'auto_stories',
    'library_books',
    'science',
    'child_care',
    'pets',
    'child_friendly',
    'family_restroom',
    'volunteer_activism',
    'favorite',
    'star',
    'flag',
    'bolt',
    'auto_awesome',
    'gps_fixed',
    'lightbulb',
    'local_offer',
    'verified',
    'category',
  ];

  static const List<IconData> kAccountIcons = <IconData>[
    Icons.account_balance,
    Icons.account_balance_wallet,
    Icons.credit_card,
    Icons.wallet,
    Icons.payments,
    Icons.savings,
    Icons.local_atm,
    Icons.attach_money,
    Icons.currency_rupee,
    Icons.currency_bitcoin,
    Icons.card_giftcard,
    Icons.apartment,
    Icons.work,
    Icons.school,
    Icons.home,
    Icons.flight,
    Icons.store,
    Icons.shopping_bag,
    Icons.favorite,
    Icons.trending_up,
  ];

  static const List<IconData> kCategoryIcons = <IconData>[
    Icons.wallet,
    Icons.credit_card,
    Icons.account_balance,
    Icons.savings,
    Icons.payments,
    Icons.local_atm,
    Icons.card_giftcard,
    Icons.assignment_return,
    Icons.restaurant,
    Icons.fastfood,
    Icons.local_cafe,
    Icons.local_bar,
    Icons.lunch_dining,
    Icons.local_grocery_store,
    Icons.local_drink,
    Icons.cake,
    Icons.directions_car,
    Icons.two_wheeler,
    Icons.electric_scooter,
    Icons.directions_bus,
    Icons.train,
    Icons.flight,
    Icons.local_gas_station,
    Icons.local_taxi,
    Icons.shopping_cart,
    Icons.shopping_bag,
    Icons.checkroom,
    Icons.devices,
    Icons.weekend,
    Icons.redeem,
    Icons.electrical_services,
    Icons.water_drop,
    Icons.local_fire_department,
    Icons.wifi,
    Icons.phone_android,
    Icons.house,
    Icons.subscriptions,
    Icons.receipt_long,
    Icons.local_hospital,
    Icons.medication,
    Icons.fitness_center,
    Icons.emergency,
    Icons.psychology,
    Icons.movie,
    Icons.music_note,
    Icons.sports_esports,
    Icons.menu_book,
    Icons.sports_soccer,
    Icons.live_tv,
    Icons.content_cut,
    Icons.spa,
    Icons.face,
    Icons.watch,
    Icons.palette,
    Icons.auto_awesome,
    Icons.home,
    Icons.build,
    Icons.handyman,
    Icons.cleaning_services,
    Icons.chair,
    Icons.hotel,
    Icons.luggage,
    Icons.beach_access,
    Icons.hiking,
    Icons.card_travel,
    Icons.tour,
    Icons.work,
    Icons.business_center,
    Icons.laptop,
    Icons.groups,
    Icons.print,
    Icons.school,
    Icons.auto_stories,
    Icons.library_books,
    Icons.science,
    Icons.child_care,
    Icons.pets,
    Icons.child_friendly,
    Icons.family_restroom,
    Icons.volunteer_activism,
    Icons.favorite,
    Icons.star,
    Icons.flag,
    Icons.bolt,
    Icons.auto_awesome,
    Icons.gps_fixed,
    Icons.lightbulb,
    Icons.local_offer,
    Icons.verified,
    Icons.category,
  ];

  static const Map<String, List<String>> kIconTags = iconTags;

  static const _iconMap = <String, IconData>{
    'account_balance': Icons.account_balance,
    'account_balance_wallet': Icons.account_balance_wallet,
    'credit_card': Icons.credit_card,
    'wallet': Icons.wallet,
    'payments': Icons.payments,
    'savings': Icons.savings,
    'local_atm': Icons.local_atm,
    'attach_money': Icons.attach_money,
    'currency_rupee': Icons.currency_rupee,
    'currency_bitcoin': Icons.currency_bitcoin,
    'card_giftcard': Icons.card_giftcard,
    'apartment': Icons.apartment,
    'work': Icons.work,
    'school': Icons.school,
    'home': Icons.home,
    'flight': Icons.flight,
    'store': Icons.store,
    'shopping_bag': Icons.shopping_bag,
    'favorite': Icons.favorite,
    'trending_up': Icons.trending_up,
    'assignment_return': Icons.assignment_return,
    'restaurant': Icons.restaurant,
    'fastfood': Icons.fastfood,
    'local_cafe': Icons.local_cafe,
    'local_bar': Icons.local_bar,
    'lunch_dining': Icons.lunch_dining,
    'local_grocery_store': Icons.local_grocery_store,
    'local_drink': Icons.local_drink,
    'cake': Icons.cake,
    'directions_car': Icons.directions_car,
    'two_wheeler': Icons.two_wheeler,
    'electric_scooter': Icons.electric_scooter,
    'directions_bus': Icons.directions_bus,
    'train': Icons.train,
    'local_gas_station': Icons.local_gas_station,
    'local_taxi': Icons.local_taxi,
    'shopping_cart': Icons.shopping_cart,
    'checkroom': Icons.checkroom,
    'devices': Icons.devices,
    'weekend': Icons.weekend,
    'redeem': Icons.redeem,
    'electrical_services': Icons.electrical_services,
    'water_drop': Icons.water_drop,
    'local_fire_department': Icons.local_fire_department,
    'wifi': Icons.wifi,
    'phone_android': Icons.phone_android,
    'house': Icons.house,
    'subscriptions': Icons.subscriptions,
    'receipt_long': Icons.receipt_long,
    'local_hospital': Icons.local_hospital,
    'medication': Icons.medication,
    'fitness_center': Icons.fitness_center,
    'emergency': Icons.emergency,
    'psychology': Icons.psychology,
    'movie': Icons.movie,
    'music_note': Icons.music_note,
    'sports_esports': Icons.sports_esports,
    'menu_book': Icons.menu_book,
    'sports_soccer': Icons.sports_soccer,
    'live_tv': Icons.live_tv,
    'content_cut': Icons.content_cut,
    'spa': Icons.spa,
    'face': Icons.face,
    'watch': Icons.watch,
    'palette': Icons.palette,
    'auto_awesome': Icons.auto_awesome,
    'build': Icons.build,
    'handyman': Icons.handyman,
    'cleaning_services': Icons.cleaning_services,
    'chair': Icons.chair,
    'hotel': Icons.hotel,
    'luggage': Icons.luggage,
    'beach_access': Icons.beach_access,
    'hiking': Icons.hiking,
    'card_travel': Icons.card_travel,
    'tour': Icons.tour,
    'business_center': Icons.business_center,
    'laptop': Icons.laptop,
    'groups': Icons.groups,
    'print': Icons.print,
    'auto_stories': Icons.auto_stories,
    'library_books': Icons.library_books,
    'science': Icons.science,
    'child_care': Icons.child_care,
    'pets': Icons.pets,
    'child_friendly': Icons.child_friendly,
    'family_restroom': Icons.family_restroom,
    'volunteer_activism': Icons.volunteer_activism,
    'star': Icons.star,
    'flag': Icons.flag,
    'bolt': Icons.bolt,
    'gps_fixed': Icons.gps_fixed,
    'lightbulb': Icons.lightbulb,
    'local_offer': Icons.local_offer,
    'verified': Icons.verified,
    'category': Icons.category,
    'storefront': Icons.storefront,
    'celebration': Icons.celebration,
    'show_chart': Icons.show_chart,
    'pie_chart': Icons.pie_chart,
    'more_horiz': Icons.more_horiz,
    'power': Icons.power,
    'shopping_basket': Icons.shopping_basket,
    'event': Icons.event,
    'person': Icons.person,
    'monetization_on': Icons.monetization_on,
    'swap_horiz': Icons.swap_horiz,
    'tune': Icons.tune,
    'handshake': Icons.handshake,
    'payments_outlined': Icons.payments_outlined,
    'account_balance_outlined': Icons.account_balance_outlined,
    'credit_card_outlined': Icons.credit_card_outlined,
  };

  static const _labelMap = <String, String>{
    'account_balance': 'Bank',
    'account_balance_wallet': 'Wallet',
    'credit_card': 'Card',
    'wallet': 'Wallet',
    'payments': 'Cash',
    'savings': 'Savings',
    'local_atm': 'ATM',
    'attach_money': 'Money',
    'currency_rupee': 'Rupee',
    'currency_bitcoin': 'Crypto',
    'card_giftcard': 'Gift',
    'apartment': 'Property',
    'work': 'Work',
    'school': 'School',
    'home': 'House',
    'flight': 'Flight',
    'store': 'Shop',
    'shopping_bag': 'Shopping',
    'favorite': 'Heart',
    'trending_up': 'Invest',
    'assignment_return': 'Refund',
    'restaurant': 'Dining',
    'fastfood': 'FastFood',
    'local_cafe': 'Coffee',
    'local_bar': 'Drinks',
    'lunch_dining': 'Pizza',
    'local_grocery_store': 'Grocery',
    'local_drink': 'Tea',
    'cake': 'Dessert',
    'directions_car': 'Car',
    'two_wheeler': 'Bike',
    'electric_scooter': 'Scooter',
    'directions_bus': 'Bus',
    'train': 'Train',
    'local_gas_station': 'Fuel',
    'local_taxi': 'Taxi',
    'shopping_cart': 'Cart',
    'checkroom': 'Clothes',
    'devices': 'Electronics',
    'weekend': 'Furniture',
    'redeem': 'Deals',
    'electrical_services': 'Electric',
    'water_drop': 'Water',
    'local_fire_department': 'Gas',
    'wifi': 'Internet',
    'phone_android': 'Phone',
    'house': 'Rent',
    'subscriptions': 'Subscription',
    'receipt_long': 'Bill',
    'local_hospital': 'Medical',
    'medication': 'Pharmacy',
    'fitness_center': 'Fitness',
    'emergency': 'Hospital',
    'psychology': 'Therapy',
    'movie': 'Movie',
    'music_note': 'Music',
    'sports_esports': 'Gaming',
    'menu_book': 'Books',
    'sports_soccer': 'Sports',
    'live_tv': 'Streaming',
    'content_cut': 'Haircut',
    'spa': 'Beauty',
    'face': 'Personal',
    'watch': 'Watch',
    'palette': 'Hobby',
    'auto_awesome': 'Sparkle',
    'build': 'Repair',
    'handyman': 'Maintenance',
    'cleaning_services': 'Cleaning',
    'chair': 'Chair',
    'hotel': 'Hotel',
    'luggage': 'Luggage',
    'beach_access': 'Beach',
    'hiking': 'Mountains',
    'card_travel': 'Holiday',
    'tour': 'Tour',
    'business_center': 'Briefcase',
    'laptop': 'Laptop',
    'groups': 'Meeting',
    'print': 'Print',
    'auto_stories': 'Course',
    'library_books': 'Library',
    'science': 'Science',
    'child_care': 'Children',
    'pets': 'Pet',
    'child_friendly': 'Baby',
    'family_restroom': 'Family',
    'volunteer_activism': 'Care',
    'star': 'Star',
    'flag': 'Flag',
    'bolt': 'Bolt',
    'gps_fixed': 'Target',
    'lightbulb': 'Idea',
    'local_offer': 'Tag',
    'verified': 'Verified',
    'category': 'Other',
    'storefront': 'Store',
    'celebration': 'Party',
    'show_chart': 'Chart',
    'pie_chart': 'Pie',
    'more_horiz': 'More',
    'power': 'Power',
    'shopping_basket': 'Grocery',
    'event': 'Events',
    'person': 'Person',
    'monetization_on': 'Bonus',
    'swap_horiz': 'Transfer',
    'tune': 'Adjust',
    'handshake': 'Loan',
    'payments_outlined': 'Cash',
    'account_balance_outlined': 'Bank',
    'credit_card_outlined': 'Card',
  };

  static IconData fromString(String name) {
    return _iconMap[name] ?? Icons.category;
  }

  static String labelFor(String name) {
    return _labelMap[name] ?? _titleCase(name);
  }

  static String toStringName(IconData icon) {
    return _iconMap.entries
        .firstWhere(
          (entry) => entry.value == icon,
          orElse: () => const MapEntry('category', Icons.category),
        )
        .key;
  }

  static String _titleCase(String value) {
    final words = value
        .replaceAll('_outlined', '')
        .split('_')
        .where((word) => word.isNotEmpty)
        .map((word) => '${word[0].toUpperCase()}${word.substring(1)}');
    return words.join(' ');
  }

  static IconData fromCurrencyCode(String code) {
    switch (code) {
      case 'INR':
        return Icons.currency_rupee_rounded;
      case 'USD':
      case 'AUD':
      case 'CAD':
      case 'SGD':
      case 'HKD':
      case 'MXN':
      case 'BRL':
        return Icons.attach_money_rounded;
      case 'EUR':
        return Icons.euro_rounded;
      case 'GBP':
        return Icons.currency_pound_rounded;
      case 'JPY':
      case 'CNY':
        return Icons.currency_yen_rounded;
      case 'KRW':
        return Icons.payments_rounded;
      case 'TRY':
        return Icons.currency_lira_rounded;
      case 'RUB':
        return Icons.currency_ruble_rounded;
      case 'BTC':
        return Icons.currency_bitcoin_rounded;
      case 'THB':
        return Icons.payments_rounded;
      default:
        return Icons.payments_rounded;
    }
  }
}
