import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:intl/intl.dart';

import '../../../core/theme/app_theme.dart';
import '../../../core/utils/color_harmonizer.dart';
import '../../../core/utils/icon_mapper.dart';
import '../../../shared/widgets/category_icon.dart';
import '../../../shared/widgets/kuber_bottom_sheet.dart';
import '../../../shared/widgets/kuber_empty_state.dart';
import '../../accounts/providers/account_provider.dart';
import '../../categories/providers/category_provider.dart';
import '../../settings/providers/settings_provider.dart';
import '../../transactions/data/transaction.dart';
import '../data/recurring_rule.dart';
import '../providers/recurring_provider.dart';

class RecurringHistorySheet extends ConsumerWidget {
  final RecurringRule rule;

  const RecurringHistorySheet({super.key, required this.rule});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final historyAsync =
        ref.watch(recurringRuleTransactionsProvider(rule.id));

    return KuberBottomSheet(
      title: 'Transaction History',
      subtitle: rule.name,
      child: historyAsync.when(
        loading: () => const Padding(
          padding: EdgeInsets.symmetric(vertical: 48),
          child: Center(child: CircularProgressIndicator()),
        ),
        error: (err, _) => Padding(
          padding: const EdgeInsets.symmetric(vertical: 48),
          child: Center(
            child: Text(
              'Error loading history: $err',
              style: GoogleFonts.inter(
                color: Theme.of(context).colorScheme.error,
              ),
            ),
          ),
        ),
        data: (transactions) {
          if (transactions.isEmpty) {
            return const KuberEmptyState(
              icon: Icons.history_rounded,
              title: 'No Transactions Yet',
              description:
                  'Transactions generated by this automation will appear here.',
            );
          }

          // Group by date (year + month + day)
          final grouped = <String, List<Transaction>>{};
          for (final t in transactions) {
            final key = DateFormat('yyyy-MM-dd').format(t.createdAt);
            grouped.putIfAbsent(key, () => []).add(t);
          }

          // Sort groups newest-first (keys are ISO date strings so string sort works)
          final sortedKeys = grouped.keys.toList()
            ..sort((a, b) => b.compareTo(a));

          return Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              for (final key in sortedKeys) ...[
                _DateGroupHeader(dateKey: key),
                const SizedBox(height: KuberSpacing.sm),
                ...grouped[key]!.map(
                  (t) => _RecurringTxnRow(transaction: t),
                ),
                const SizedBox(height: KuberSpacing.md),
              ],
              const SizedBox(height: KuberSpacing.md),
            ],
          );
        },
      ),
    );
  }
}

// ── Date group header ─────────────────────────────────────────────────────────

class _DateGroupHeader extends StatelessWidget {
  final String dateKey; // 'yyyy-MM-dd'

  const _DateGroupHeader({required this.dateKey});

  @override
  Widget build(BuildContext context) {
    final cs = Theme.of(context).colorScheme;
    final date = DateTime.parse(dateKey);
    final now = DateTime.now();
    final today = DateTime(now.year, now.month, now.day);
    final yesterday = today.subtract(const Duration(days: 1));
    final d = DateTime(date.year, date.month, date.day);

    String label;
    if (d == today) {
      label = 'TODAY';
    } else if (d == yesterday) {
      label = 'YESTERDAY';
    } else {
      label = DateFormat('EEE, MMM d, yyyy').format(date).toUpperCase();
    }

    return Padding(
      padding: const EdgeInsets.only(bottom: 4),
      child: Text(
        label,
        style: GoogleFonts.inter(
          fontSize: 10,
          fontWeight: FontWeight.w700,
          color: cs.onSurfaceVariant,
          letterSpacing: 1.0,
        ),
      ),
    );
  }
}

// ── Transaction row ───────────────────────────────────────────────────────────

class _RecurringTxnRow extends ConsumerWidget {
  final Transaction transaction;

  const _RecurringTxnRow({required this.transaction});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final cs = Theme.of(context).colorScheme;
    final textTheme = Theme.of(context).textTheme;
    final formatter = ref.watch(formatterProvider);

    final categoryMapAsync = ref.watch(categoryMapProvider);
    final accountsAsync = ref.watch(accountListProvider);

    final catId = int.tryParse(transaction.categoryId);
    final cat = categoryMapAsync.whenOrNull(data: (m) => catId != null ? m[catId] : null);

    final accountName = accountsAsync.whenOrNull(
      data: (accs) => accs
          .where((a) => a.id.toString() == transaction.accountId)
          .firstOrNull
          ?.name,
    );

    final iconData = cat != null
        ? IconMapper.fromString(cat.icon)
        : Icons.category_outlined;
    final rawColor = cat != null ? Color(cat.colorValue) : cs.outline;
    final iconColor = harmonizeCategory(context, rawColor);

    final isIncome = transaction.type == 'income';
    final amountColor = isIncome ? cs.tertiary : cs.error;
    final amountPrefix = isIncome ? '+' : '-';

    final timeStr = DateFormat('h:mm a').format(transaction.createdAt);

    return Container(
      margin: const EdgeInsets.only(bottom: KuberSpacing.sm),
      padding: const EdgeInsets.all(KuberSpacing.md),
      decoration: BoxDecoration(
        color: cs.surfaceContainerHigh,
        borderRadius: BorderRadius.circular(KuberRadius.md),
        border: Border.all(color: cs.outline, width: 0.5),
      ),
      child: Row(
        children: [
          CategoryIcon.square(
            icon: iconData,
            rawColor: iconColor,
            size: 44,
          ),
          const SizedBox(width: KuberSpacing.md),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  transaction.name,
                  style: textTheme.bodyMedium?.copyWith(
                    fontWeight: FontWeight.w600,
                    color: cs.onSurface,
                  ),
                  overflow: TextOverflow.ellipsis,
                ),
                const SizedBox(height: 2),
                Text(
                  [
                    cat?.name ?? 'Unknown',
                    accountName,
                    timeStr,
                  ].whereType<String>().join(' · '),
                  style: textTheme.labelSmall?.copyWith(
                    color: cs.onSurfaceVariant,
                  ),
                ),
              ],
            ),
          ),
          const SizedBox(width: KuberSpacing.sm),
          Text(
            '$amountPrefix${formatter.formatCurrency(transaction.amount)}',
            style: textTheme.bodyMedium?.copyWith(
              color: amountColor,
              fontWeight: FontWeight.w600,
            ),
          ),
        ],
      ),
    );
  }
}
